### ISSUE TITLE
[docs]: WalletConnect V2 disconnect / killSession

### ISSUE THREAD

**Issue by Z-Hayk** [WalletConnect/modal-react-native#14]
### Summary

Hello.
I can't disconnect.

In version 1 -> useWalletConnect().killSession()
https://docs.walletconnect.com/1.0/client-api#kill-session-disconnect

But version 2 doesn't have it.
Version 2 has useWalletConnectModal().provider.disconnect()
But it doesn't work, it doesn't clear the session.

I am using this example.
https://github.com/WalletConnect/react-native-examples/tree/main/dapps/v2Explorer

### Link to the related docs page

https://docs.walletconnect.com/1.0/client-api#kill-session-disconnect

**Comment by emzet93** [comment]
@Z-Hayk how did you manage to solve it?

`provider.disconnect()` works, although sometimes it requires few seconds to resolve and doesn't work at all if there is no internet connection (doesn't throw error).

In v1 it was always instant. Is there any way to improve it?

**Comment by Z-Hayk** [comment]
@emzet93 Hello.

Yes, this is how I do it.
```
provider.disconnect()
```

But I agree with you, sometimes it doesn't work sometimes for a long time and if there is no Internet it doesn't work.

I open this issue.

**Comment by ignaciosantise** [comment]
@Z-Hayk @emzet93 `provider.disconnect()` isn't instantaneous because it send's the disconnect message to the relay and waits for confirmation before clearing the session locally. By doing that, we assure the session is closed in both the dapp and the wallet. 

If you don't have internet connection, the provider waits until the connection is established to send the message. We are currently working on some changes to improve UX and show errors in those cases.

**Comment by Z-Hayk** [comment]
@ignaciosantise Hello. Thanks for the answer. Okay, but in V1 everything worked faster, and if there is no Internet, then how to clear the session?

**Comment by emzet93** [comment]
> @Z-Hayk @emzet93 `provider.disconnect()` isn't instantaneous because it send's the disconnect message to the relay and waits for confirmation before clearing the session locally. By doing that, we assure the session is closed in both the dapp and the wallet.
> 
> If you don't have internet connection, the provider waits until the connection is established to send the message. We are currently working on some changes to improve UX and show errors in those cases.

Ah ok, thanks for clarification! However I'm wondering what are the risks of not waiting for relay response?

I mean the case:
1. Press disconnect
2. Update the UI to not connected state optimistically
3. Clear session locally
4. Disconnect message to relay fails

What kind of issues can it produce? Will it make re-connecting or connecting to different wallet impossible or something?

I'm asking because I would just want to assure better UX with instant disconnect effect for a user.

**Comment by ignaciosantise** [comment]
@emzet93 by clearing the session locally without waiting for the relay confirmation but then the session would be left active on the other peer until it expires. In this case, the wallet will show the existing connection.

**Comment by emzet93** [comment]
@ignaciosantise thanks. Just out of curiosity - how did it work in v1, where `killSession` worked instantly and even without internet connection? 🤔
