### ISSUE TITLE
[feature] wrap modal into a wagmi connector

### ISSUE THREAD

**Issue by m1heng** [WalletConnect/modal-react-native#95]
### What problem does this new feature solve?

make modal-react-native more easier to be integrated into a wagmi project, instead of integrate the entire web3modal

### Describe the solution you'd like

```
import { WalletconnectModalReactNativeConnector } from "@walletconnect/modal-react-native";

const config = createConfig({
    // ...
    connectors: [
        // ...
        new WalletconnectModalReactNativeConnector({
            chains,
        }),
    ],
});
```

**Comment by glitch-txs** [comment]
what's the issue with the current Web3Modal for React Native? We added some improvements for Wagmi to work correctly in React Native.

**Comment by m1heng** [comment]
@glitch-txs the thing is that, Web3Modal is a full wrap of wagmi, where user can't add more connectors in like a connector form specific wallet.

When using Web3Modal, we can't have Walletconnect as an option but the only option.

**Comment by glitch-txs** [comment]
The idea of Web3Modal is to integrate and support all Wagmi connectors, we're currently working with Coinbase and we'll be adding more in the feature if they are requested. We'll need to build some of them from scratch since they are browser specific.

**Comment by glitch-txs** [comment]
Is there any connector you'd like us to support?

**Comment by m1heng** [comment]
no specifically. The idea of this issue is make this repo more extendable, that's why I said in the first "instead of integrate the entire web3modal"

**Comment by glitch-txs** [comment]
The main idea with Web3Modal is to be able to integrate different connectors, we'll launch soon support for the Coinbase connector. 

If you'd like to create a custom modal you can copy our WalletConnect connector and customize it to your liking, since it's the only thing we changed to Wagmi (besides some polyfills)

This modal is for more low level purposes so we're not planning to add too many features to it.
